# Generated by Django 5.1.2 on 2024-10-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='photo_description',
            field=models.CharField(blank=True, help_text='Descripción de la foto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='video_description',
            field=models.CharField(blank=True, help_text='Descripción del video', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
