# Generated by Django 5.1.2 on 2024-10-26 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_remove_surveyresponse_submitted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='photo_description',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='video',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='video_description',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('description', models.CharField(blank=True, help_text='Descripción de la foto', max_length=255, null=True)),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='encuesta.surveyresponse')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/')),
                ('description', models.CharField(blank=True, help_text='Descripción del video', max_length=255, null=True)),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='encuesta.surveyresponse')),
            ],
        ),
    ]
